[package]
name = "device"
version = "0.0.1"
authors = ["The Servo Project Developers"]

[features]
default = ["bluetooth"]
bluetooth = ["blurz"]

[target.'cfg(target_os = "linux")'.dependencies]
blurz = { version = "0.2.0", optional = true }
