[package]
name = "device"
version = "0.0.1"
authors = ["The Servo Project Developers"]
edition = "2018"

[features]
bluetooth = ["blurz", "blurdroid", "blurmac"]
bluetooth-test = ["blurmock"]

[target.'cfg(target_os = "linux")'.dependencies]
blurz = { version = "0.3", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
blurdroid = { version = "0.1.2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
blurmac = { path = "blurmac", optional = true }

[dependencies]
blurmock = { version = "0.1.2", optional = true }
